name: CI
on:
  push:
    branches:
      - main

jobs:  
  test-with-torque:
    runs-on: ubuntu-latest
    
    steps:
    - name: Start Torque Sandbox
      id: start-sandbox
      uses: kalsky/torque-start-sb-action@v0.0.4
      with:
        space: Sample
        blueprint_name: autogen_eks-rds--Sample
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        torque_alt_url: https://review1.qualilabs.net
        duration: 120
        timeout: 30
        artifacts: ''
        inputs: ''


